name: 'Damm DevOps - Gitflow branch naming restriction'
description: 'Gitflow branch naming restriction'

inputs:
  default-branch-name:
    description: 'Default branch name (usually main or master)'
    default: ${{ github.event.repository.default_branch }}

outputs:
  branch-naming-allowed:
    description: 'Boolean output indicating if the push branch name is allowed.'

runs:
  using: 'node12'
  main: 'dist/app.js'

branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
