name: 'Damm DevOps - Gitflow branch naming restriction'
description: 'Gitflow branch naming restriction'

outputs:
  branch_naming_allowed:
    description: 'Boolean output indicating if the push branch name is allowed.'
    value: ${{ steps.run-script.outputs.branch_naming_allowed }}

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '12'
    - run: export DEFAULT_BRANCH_NAME=${{ github.event.repository.default_branch }} && export GITHUB_TOKEN=${{ github.token }} && cd ${{ github.action_path }} && npm install && node dist/app.js
      shell: bash
      id: run-script

branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
